from typing import Protocol
from schemas.films import Film, NewFilm


class IFilmRepository(Protocol):

    async def get_all_films(self) -> list[Film]: ...

    async def add_film(self, film: NewFilm, image_url: str | None = None) -> Film: ...

    async def get_by_id(self, id: int) -> Film | None: ...

    async def delete(self, id: int) -> None: ...
